-- -- Add up migration script here
-- -- Add up migration script here
-- CREATE TYPE question_type AS ENUM ('single_choice', 'multiple_choice', 'true_false', 'short_answer');

-- -- Quizzes table (created by admins)
-- CREATE TABLE quizzes (
--     id UUID PRIMARY KEY,
--     title TEXT NOT NULL,
--     description TEXT,
--     created_by UUID NOT NULL REFERENCES users(id),
--     is_active BOOLEAN NOT NULL DEFAULT TRUE,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Questions belonging to a quiz
-- CREATE TABLE questions (
--     id UUID PRIMARY KEY,
--     quiz_id UUID NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
--     question_text TEXT NOT NULL,
--     question_type question_type NOT NULL DEFAULT 'single_choice',
--     points INTEGER NOT NULL DEFAULT 1,
--     order_num INTEGER NOT NULL DEFAULT 0,  -- for ordering questions in quiz
--     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Possible answers/options for each question
-- -- For single/multiple choice: multiple rows per question
-- -- For true/false: two rows (true/false)
-- -- For short_answer: no rows or one "correct_answer" TEXT field (but we'll use options table for consistency)
-- CREATE TABLE question_options (
--     id UUID PRIMARY KEY,
--     question_id UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
--     option_text TEXT NOT NULL,
--     is_correct BOOLEAN NOT NULL DEFAULT FALSE
-- );

-- -- Student attempts (one row per quiz attempt by student)
-- CREATE TABLE quiz_attempts (
--     id UUID PRIMARY KEY,
--     user_id UUID NOT NULL REFERENCES users(id),
--     quiz_id UUID NOT NULL REFERENCES quizzes(id),
--     started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     completed_at TIMESTAMPTZ,
--     score INTEGER DEFAULT 0,
--     max_score INTEGER NOT NULL,  -- precomputed total points of quiz
--     status TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed', 'abandoned'))
-- );

-- -- Individual answers given by student during attempt
-- CREATE TABLE attempt_answers (
--     id UUID PRIMARY KEY,
--     attempt_id UUID NOT NULL REFERENCES quiz_attempts(id) ON DELETE CASCADE,
--     question_id UUID NOT NULL REFERENCES questions(id),
--     selected_option_id UUID REFERENCES question_options(id),  -- for choice questions
--     short_answer TEXT,  -- for short answer questions
--     is_correct BOOLEAN,  -- computed on submission
--     points_earned INTEGER DEFAULT 0
-- );

-- -- Indexes for performance
-- CREATE INDEX idx_quizzes_created_by ON quizzes(created_by);
-- CREATE INDEX idx_questions_quiz_id ON questions(quiz_id);
-- CREATE INDEX idx_quiz_attempts_user_id ON quiz_attempts(user_id);
-- CREATE INDEX idx_quiz_attempts_quiz_id ON quiz_attempts(quiz_id);
-- CREATE INDEX idx_attempt_answers_attempt_id ON attempt_answers(attempt_id);
